### ISSUE TITLE
UnrecognizedPropertyException thrown on following element, when empty list without <list/> item present

### ISSUE THREAD

**Issue by arberg** [FasterXML/jackson-dataformat-xml#189]
This is moved from here: https://github.com/FasterXML/jackson-databind/issues/1151#issuecomment-192479681. I have uploaded source code here (Android gradle project): [AndroidProjectTest](http://www.filedropper.com/alexjacksonxmltestissuetracking) and a copy here at my google drive [AndroidProjectTest](https://drive.google.com/open?id=0B7dZG1Tg5cbmLUIwTmJIdnJodTA)

Under some apparently special circumstances I'll get the error

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "central" (class model.Host), not marked as ignorable (4 known properties: "port", "centraler", "name", "url"])
at Source: java.io.StringReader@307f6b8; line: 16, column: 2

when I have XML like this

```
        <host name="bnr" url="x.x.x.x" port="8080">
            <centraler>
                <central name="BNR Taxa">
                    <vehicletypes>
                        <vehicletype >
                            <capability category="A" name="childseat" />
                        </vehicletype>                      
                        <vehicletype name="largevehicle">
                        </vehicletype>
                    </vehicletypes>
                </central>
                <central name="BNR Taxa">
                </central>
            </centraler>
        </host>

```
If the second vehicletype 
1) does not contain an attribute, or 
2) closes like this , or
3) has a capability or 
then it parses correctly

It is also a requirement that its in a 'centraler' list, if I just parse the 'central' it does not fail, even when I add a tag after vehicletypes that make the above fail earlier. It seems Jackson is in a state where it will fail at the next opening element after parsing the last vehicletype.

I can supply a small test which contains the problem. Its written as an Android junit test, but is self-contained.

I use these libs (I don't know if that might be relevant). Tested on version jackson 2.7.2.

```
    testCompile 'junit:junit:4.12'
    compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:+'
// for pretty print
    compile 'org.codehaus.woodstox:woodstox-core-asl:+'
// does not have pretty print, but still has bug
//    compile 'javax.xml.stream:stax-api:+'

    compile 'com.fasterxml.jackson.core:jackson-core:+'
    compile 'com.fasterxml.jackson.core:jackson-annotations:+'
    compile 'com.fasterxml.jackson.core:jackson-databind:+'

```
Best Alex

**Comment by cowtowncoder** [comment]
Thank you for reproduction. I would suggest trying out 2.7.4, just in case, as #191 (which was fixed) could be related.

I hope to look into this soon, haven't yet had time.

**Comment by arberg** [comment]
I've run my unit-test again on the new version 2.7.4 and this time it works. It still fails on 2.7.3, so I can happily report that 2.7.4 fixes the issue. 

Awesome, thank you :)

Best Alex

**Comment by cowtowncoder** [comment]
@arberg Excellent! Wasn't sure it would but seemed plausible. Thank you for verifying.
